### https://www.jetbrains.com/help/idea/exploring-http-syntax.html#enable-disable-redirects
### request all states
GET http://localhost:8080/statuses

### Request a single Status
GET localhost:8080/statuses/{{status_id}}

### Vote on a status down

POST {{host}}/statuses/vote
Content-Type: application/json

{
  "direction": false,
  "id":  {
  "userId": "1000",
  "entityId": "5f309adb3dd75b62ddacf344"
  }
}

### Vote on a status up

POST {{host}}/statuses/vote
Content-Type: application/json

{
  "direction": true,
  "id":  {
  "userId": "1000",
  "entityId": "5f309adb3dd75b62ddacf344"
  }
}

### remove the last vote I did and undo what ever the vote was
POST {{host}}/statuses/vote/delete
Content-Type: application/json

{
  "id":  {
    "userId": "1000",
    "entityId": "5f309adb3dd75b62ddacf344"
  }
}

### ---- COMMENTS ----

### post comment

POST {{host}}/statuses/5f309adb3dd75b62ddacf344/comments
Content-Type: application/json

{
  "body": "gg hhhhhhhh vfdgfdgfdggdfgdfgdfgfdg"
}

### get comments
GET {{host}}/statuses/5f309adb3dd75b62ddacf344/comments
Content-Type: application/json

### --- Vote on comments ---- DOES NOt work!!!

POST {{host}}/statuses/5f309adb3dd75b62ddacf344/comments/vote
Content-Type: application/json

{
  "direction": true,
  "id":  {
    "userId": "1000",
    "entityId": "5f37c3129da8811a712443b9"
  }
}

### remove the last vote I did and undo what ever the vote was
POST {{host}}/statuses/5f309adb3dd75b62ddacf344/comments/vote/delete
Content-Type: application/json

{
  "id":  {
    "userId": "1000",
    "entityId": "5f37c3129da8811a712443b9"
  }
}

